# Copyright (C) 2026 iceman50
# Licensed under GPL-3.0-or-later.

Import("dev source_path")

env, target, sources = dev.prepare_build(
    source_path, "BBS0", shared_precompiled_header="stdinc"
)
env["SHLIBPREFIX"] = ""

env.Append(CPPPATH=["#"])
env.Append(LIBS=["adchpp"])

ret = env.SharedLibrary(target, sources)

Return("ret")
